#!/bin/sh
# postinst script for #PACKAGE#

set -e


case "$1" in
    configure)
	cp -a /usr/share/siduction/snapper-config.sh /usr/local/bin/
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
