#!/bin/bash

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")

cat <<EOF > $CHROOT/etc/apt/sources.list
# Debian
deb http://deb.debian.org/debian stretch main
deb-src http://http.debian.net/debian stretch main
deb http://deb.debian.org/debian-security stretch-updates
deb-src http://deb.debian.org/debian-security stretch-updates

EOF
